# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20180317_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitem',
            name='temp_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
