# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loggedinuser',
            table='auth_logged',
        ),
    ]
