AWS_UPLOAD_BUCKET = "freemedianews"

AWS_UPLOAD_USERNAME = "freemedia"

AWS_UPLOAD_GROUP = "freemedia"

AWS_UPLOAD_REGION = 'ap-southeast-1'

AWS_UPLOAD_ACCESS_KEY_ID = "AKIAJ6PAHRZ7SF6G6XVA"

AWS_UPLOAD_SECRET_KEY = "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"