# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20180113_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='global', max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='country_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='feeds.Country'),
        ),
    ]
