# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20180323_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='youtube_link',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
