# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-25 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_feed_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='country_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_country', to='feeds.Country'),
        ),
    ]
